# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleApp
  pod 'x_kmm_module_core', :path => '../../sharedmodule/x_kmm_module_core'
  pod 'x_kmm_module_a', :path => '../../sharedmodule/x_kmm_module_a'

  target 'ExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleAppUITests' do
    # Pods for testing
  end

end
